edition = "2021"
force_explicit_abi = true
format_code_in_doc_comments = true
group_imports = "One"
hard_tabs = false
imports_granularity = "Crate"
indent_style = "Block"
max_width = 130
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = false
